### ISSUE TITLE
Instructions for additional "Installation" options

### ISSUE THREAD

**Issue by BinToss** [teeteeteeteetee/adobe-discord-rpc#46]
Releasing with the redundant ZXP file type grants a few more options for installing `com.discord.rpc.tee`. Because Adobe Extension Manager is deprecated, these two open source GUI solutions provide alternatives to both the old Adobe Extension Manager and the modern (but unintuitive for unapproved plugins) Creative Cloud Desktop app.

## Adobe's [Unified Plugin Installer Agent](https://helpx.adobe.com/creative-cloud/help/working-from-the-command-line.html)
Included with Creative Cloud 5.5+

## [Anastasiy’s Extension Manager](http://install.anastasiy.com/)
> Adobe® Creative Suite/Cloud/XD extension management made easy!
now with install/remove/update support. [Recommended by Adobe®](https://blog.anastasiy.com/?p=1751)

AEM provides an alternative to Creative Cloud Desktop's plugin installation and management framework.
At the time of this writing, AEM 3.7 is the latest release for macOS 10.8+ and Windows 7+ with support for CC 2014-2022
## [ZXPInstaller](https://zxpinstaller.com/)
A wrapper for the old Adobe Extension Manager command line utility (ExMan). Its releases include the necessary Adobe binaries.
> An open source Adobe extension installer
> | It will | It will not
> |----|----
> | Install your .zxp extensions | Manage or uninstall your extensions
> 
> ZXPInstaller is a simple cross platform (OS X and Windows) installer for third party Adobe extensions (.zxp files). It serves as a replacement for the Extension Manager which is not supported after CC 2014. It provides a drag-and-drop GUI for installation, and [a website](https://zxpinstaller.com/) to which extension developers can point users to download the installer.
> ## How it works
> ZXPInstaller uses [Electron](https://electron.org/) to create a cross platform HTML/node.js app. The app spawns a child process for the _Adobe Extension Manager_ command line utility to install the ZXP.

**Comment by lolitee** [comment]
can u create a pull request for it?
