### ISSUE TITLE
Abnormal behaviors with Audition

### ISSUE THREAD

**Issue by Kakaka999** [teeteeteeteetee/adobe-discord-rpc#49]
I'm using Audition 14.4.3, and discord rpc does not behave normal. Sometimes it does not recognize Audition at all, or it shows my session project as "Multitrack" or "WaveDocument", not the session project's name.

**Comment by lolitee** [comment]
Its intentionally im pretty sure i had issues getting the project name from the api, ill look on it when ill have the time

**Comment by lolitee** [comment]
nevermind i fucked up something

**Comment by teeteeteeteetee** [comment]
fixed
