### ISSUE TITLE
Cursor flashing from tool to default when using After Effects.

### ISSUE THREAD

**Issue by LaykaKiro** [teeteeteeteetee/adobe-discord-rpc#50]
I have boiled it down to the Extension or the registry edit, there isn't much else to say/

**Comment by lolitee** [comment]
Are u sure u are on latest version because i cannot reproduce this

**Comment by LaykaKiro** [comment]
I don't think I am on the latest version of AE but I have the latest of the Extention.

**Comment by lolitee** [comment]
i meant the last version of the extension but ye what is your ae version

**Comment by lolitee** [comment]
try reinstalling the extension here https://github.com/lolitee/adobe-discord-rpc/releases/tag/v0.0.4.6-beta idk if it will help im pretty sure there was something wrong with the installation

**Comment by lolitee** [comment]
can u give me the exact version of ae it should be under help section im pretty sure so i can try to reproduce it

**Comment by LaykaKiro** [comment]
Oh, sure. I'll be a bit because I'm currently playing a game.
