### ISSUE TITLE
Firm Problem

### ISSUE THREAD

**Issue by Catgithub768** [teeteeteeteetee/adobe-discord-rpc#55]
OS: Windows 11
 I installed the extension yesterday but i couldnt use it because this error shows up on start-up
![image](https://user-images.githubusercontent.com/79985497/235030471-6061693a-c732-47cd-8bea-07707f01a054.png)

Basically what the upper text says is that the extension is not firmed correctly. So is there any way i can fix this or its just a bug?

**Comment by teeteeteeteetee** [comment]
enable debug mode in regedit
