### ISSUE TITLE
ZXP Installation Fails with Code -410

### ISSUE THREAD

**Issue by KingGamingYT** [teeteeteeteetee/adobe-discord-rpc#62]
Using both Adobe's included UPIA or Anastasiy's Extension Manager to try installing the extension results in a -410 error code, the likes of which I cannot find any information online about or any other error codes related to this.

**To Reproduce**
Attempt to install the extension via a ZXP file using either of these two methods.

**Expected behavior**
The extension installs successfully.

**Screenshots**
![image](https://github.com/teeteeteeteetee/adobe-discord-rpc/assets/45918062/82aabbdd-1861-4d76-9e93-3c72fd612477)
(UPIA and AEM have the same dialog, so I assume AEM uses UPIA with a GUI over it)

**Desktop:**
 - OS: Windows
 - Version 10, 212H

If this has already been reported, I apologize for the duplicate.

**Comment by teeteeteeteetee** [comment]
dont use the zxp, its deprecated and rarely works, zip method should be good enough
