### ISSUE TITLE
Error prompt when trying to update

### ISSUE THREAD

**Issue by AnimusN7** [teeteeteeteetee/adobe-discord-rpc#64]
Hey,

when trying to install the latest update, I get following error prompt 
![image](https://github.com/teeteeteeteetee/adobe-discord-rpc/assets/33660463/ab9d3328-5622-4b8d-ac3a-43e01fa740d0)

I have tried to look for a solution myself but wasn't successful. Any idea what this could be?

**Comment by teeteeteeteetee** [comment]
the feature is broken, you can ignore it
