### ISSUE TITLE
Releases are not from the correct repo

### ISSUE THREAD

**Issue by moon250** [teeteeteeteetee/adobe-discord-rpc#66]
**Describe the bug**
Under "Update Extension", the releases listed come from [this repo](https://github.com/lolitee/adobe-discord-rpc/releases), instead of this one. This leads to unexpected "New update available in settings" in the parameters

**To Reproduce**
1. Go to the extension page
2. Click on ⚙️
3. Under **Update Extension**

**Expected behavior**
There should be releases from this repo

**Screenshots**
Pretty much self explanatory ... 

**Desktop:**
 - OS: Windows
 - Version 11
 - Extension version v0.0.4.6-beta

**Comment by teeteeteeteetee** [comment]
the utility never worked and it has been removed in newer versions
