### ISSUE TITLE
cannot swap logo

### ISSUE THREAD

**Issue by teeteeteeteetee** [teeteeteeteetee/adobe-discord-rpc#69]

**Comment by DevLung** [comment]
**I have the same problem  ( Win10;  Premiere 24.3;  adobe-discord-rpc v0.0.2-hotfix2 )**
If I change the large icon from 'Old' to 'Updated' in the extension settings and save the config, it reverts back to 'Old' on re-opening the settings or even the tab (eg. to preview tab and back)
In discord the logo doesn't change too so it's not just a UI bug.
Any other settings are applied fine on save, except this one.

**Comment by teeteeteeteetee** [comment]
it wasnt implemented till now, im updating the extension soon

**Comment by teeteeteeteetee** [comment]
if you wanna try it out, it should be available in actions
https://github.com/teeteeteeteetee/adobe-discord-rpc/actions/runs/8588155833/artifacts/1391837167

![image](https://github.com/teeteeteeteetee/adobe-discord-rpc/assets/62479501/ead12ec2-d409-4f82-a3c2-7fc9203faad0)

**Comment by DevLung** [comment]
> if you wanna try it out, it should be available in actions here: https://github.com/teeteeteeteetee/adobe-discord-rpc/actions/runs/8588155833/artifacts/1391837167
> 
> ![image](https://private-user-images.githubusercontent.com/62479501/320275222-ead12ec2-d409-4f82-a3c2-7fc9203faad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODc5ODgsIm5iZiI6MTcxMjQ4NzY4OCwicGF0aCI6Ii82MjQ3OTUwMS8zMjAyNzUyMjItZWFkMTJlYzItZDQwOS00ZjgyLWEzYzItN2ZjOTIwM2ZhYWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExMDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjM2JmYWVkZGQzYmNiYzk3NDFmMGZlMWFhYjg1ZmQ3NmRmNGJhMDQzNDg3MDQ4ZmRjYjQxNGEzODUxODllNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PHvWnFL4YAVGe7LnqApa311cT1aqykwwfgNkJG_g2aM)

Thank you, works perfectly for me with the actions release.
