### ISSUE TITLE
doesn't work with Adobe Audition

### ISSUE THREAD

**Issue by AmizRm** [teeteeteeteetee/adobe-discord-rpc#72]
extension works fine with photoshop but not with audition

**Comment by teeteeteeteetee** [comment]
are you able to open the extension panel in audition

**Comment by AmizRm** [comment]
> are you able to open the extension panel in audition

Nope

**Comment by ddorbb** [comment]
Same issue here, works fine with all the apps I have installed (Photoshop, After Effects, Premiere Pro) except for Audition

**Comment by teeteeteeteetee** [comment]
create a ticket on discord

**Comment by teeteeteeteetee** [comment]
can you try if this version works from github actions https://github.com/teeteeteeteetee/adobe-discord-rpc/suites/18408716090/artifacts/1066722204

**Comment by AmizRm** [comment]
it fixed adobe audition problem but i have new problem now. i can't change any config options and save configuration

**Comment by teeteeteeteetee** [comment]
fixed in latest https://github.com/teeteeteeteetee/adobe-discord-rpc/releases/tag/v0.0.2
