### ISSUE TITLE
Save configuration button not working

### ISSUE THREAD

**Issue by BlackFalcon1961** [teeteeteeteetee/adobe-discord-rpc#73]
**Describe the bug:**
After i change any setting, the 'Save configuration' button not work.

**To Reproduce:**
1. Go to 'Window > Addon'
2. Click on 'Discord Rich Presence'
3. Change any setting
4. Click on 'Save configuration' button
5. See error

**Expected behavior:**
I have same issue with all Adobe apps.

**Screenshots:**
![image](https://github.com/teeteeteeteetee/adobe-discord-rpc/assets/60007836/d2b1aa21-137d-408a-81d7-6378e4704f6b)
![image](https://github.com/teeteeteeteetee/adobe-discord-rpc/assets/60007836/da93c3bf-1f3c-4e35-9ac8-901c15c91a50)
![image](https://github.com/teeteeteeteetee/adobe-discord-rpc/assets/60007836/33a3c621-6de2-4d7a-8c31-d958f9b19a4a)

**Desktop:**
 - OS: Windows 11 Home

N.B: I'm French, my english is not perfect, sorry ^^

**Comment by KingGamingYT** [comment]
This is known #67

**Comment by teeteeteeteetee** [comment]
sorry about it im kinda busy with job currently, ill try to fix it asap
https://github.com/teeteeteeteetee/adobe-discord-rpc/issues/67
