### ISSUE TITLE
Plugin does not save changes in settings 

### ISSUE THREAD

**Issue by Dawix67** [teeteeteeteetee/adobe-discord-rpc#75]
Everything I change in the settings doesn't change 
Everything I change in the settings does not change, when I want to change something in the settings it does not save and nothing changes, this applies to all adobe applications .

I'm using windwos 11, hope for help!

**Comment by teeteeteeteetee** [comment]
https://github.com/teeteeteeteetee/adobe-discord-rpc/issues/67 will be fixed today hopefully
