### ISSUE TITLE
Details & State

### ISSUE THREAD

**Issue by AmizRm** [teeteeteeteetee/adobe-discord-rpc#76]
can you hide the (hidden)? :/
![image](https://github.com/teeteeteeteetee/adobe-discord-rpc/assets/103880291/ce45d99b-5acc-4a59-ab11-69b2e374c2f3)

**Comment by teeteeteeteetee** [comment]
it would somewhat break the rpc so probably not
![obrazek](https://github.com/teeteeteeteetee/adobe-discord-rpc/assets/62479501/2b8f808b-fb10-4342-94f3-263d5ed6c217)

**Comment by teeteeteeteetee** [comment]
im dumb it works without it
