### ISSUE TITLE
Uhmmm

### ISSUE THREAD

**Issue by AmizRm** [teeteeteeteetee/adobe-discord-rpc#77]
why there isn't any button?

![image](https://github.com/teeteeteeteetee/adobe-discord-rpc/assets/103880291/464254ef-2d3e-4b4f-b869-a8bedc4a8dd0)

**Comment by AmizRm** [comment]
Adobe Photoshop 2023

**Comment by teeteeteeteetee** [comment]
try reset default and restart

**Comment by AmizRm** [comment]
didn't work

**Comment by teeteeteeteetee** [comment]
open up a ticket

**Comment by teeteeteeteetee** [comment]
fixed
