### ISSUE TITLE
RPC doesn't work with Dreamweaver

### ISSUE THREAD

**Issue by FERFAIL-TXZ** [teeteeteeteetee/adobe-discord-rpc#83]
Other programs as Photoshop, Premiere Pro or After Effects works, but Dreamweaver doesn't. It shows the default icon in the extension tab.
![image](https://github.com/teeteeteeteetee/adobe-discord-rpc/assets/66634449/e09c8803-c4da-4e11-915a-1d1ec1bd476e)

I followed the installation guide. Putting the RPC thing in the Adobe extensions folder, then going to the regedit and created a string value in every CSX numbers (In my case 10 and 11).
I'm on Windows 10 using the latest version of adobe-discord-rpc v0.0.3.

Resseting to default settings doesn't change anything, it doesn't show yet.
In previous version was the same, doesn't show.

Also, as an aditional note, the changing betwen old and new icon just doesn't work yet...

**Comment by teeteeteeteetee** [comment]
can you try https://github.com/teeteeteeteetee/adobe-discord-rpc/actions/runs/8934132141/artifacts/1469464332

**Comment by FERFAIL-TXZ** [comment]
gonna try it

**Comment by FERFAIL-TXZ** [comment]
Oh, well, that one worked... The logo thing still doesn't work _(time elapsed neither, always marks as 04:02:20)_ but ig you will take your time. Thanks man!

**Comment by teeteeteeteetee** [comment]
the logo thing will be fixed when i release new version
