### ISSUE TITLE
bug i guess

### ISSUE THREAD

**Issue by kiyxshi** [teeteeteeteetee/adobe-discord-rpc#85]
![изображение](https://github.com/user-attachments/assets/d6edc11a-ed6e-40f0-ac75-7b239bee5318)
Discord Rich Presence failed to load.
Invalid signature
Extension ID com.tee.discord-rpc-panel
Path: C:\Users\gamer\AppData\Roaming\Adobe
\CEP\extensions\com.tee.discord-rpc\index.html

got earlier this error, idk what's wrong. before this works normally...

**Comment by teeteeteeteetee** [comment]
enable debug mode in regedit

**Comment by kiyxshi** [comment]
already standing

**Comment by teeteeteeteetee** [comment]
check if u got multiple ones and put it in each of them ranging from csxs9
to csxs11

**Comment by teeteeteeteetee** [comment]
also try reinstalling the extension

**Comment by teeteeteeteetee** [comment]
but i doubt its the extension being faulty, maybe audition is being weird

**Comment by kiyxshi** [comment]
![photo_2024-02-08_05-42-08](https://github.com/user-attachments/assets/f3eb138c-49de-4fe1-b24f-96dc2c2396fa)
